name: Luis' Rodriguez ENG
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Change these two keys when you add a domain name
url: "https://lrodri29.github.io/LuisWeb"
baseurl: ""
github_username: lrodri29

# name: Luis' Rodriguez ENG
# markdown: redcarpet
# exclude: ["node_modules", "gulpfile.js", "package.json"]
# baseurl: "/LuisSite/"
# url: ""
# github_username: lrodri29
