name: Luis' Rodriguez ENG
exclude: ["node_modules", "gulpfile.js", "package.json"]

github_username: lrodri29

# Change these two keys when you add a domain name
url: https://lrodri29.github.io/LuisWeb/
baseurl: /LuisWeb
